name: Echo Issues
on: issues
jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Output GitHub Issues Title
              run: echo "${{ toJSON(github.event.issue.title) }}"
            - name: Output GitHub Issues Body
              run: echo "${{ toJSON(github.event.issue.body) }}"